hlky/stable-diffusion:
  - source: webui.py
    dest: scripts/webui.py
  - source: webui_playground.py
    dest: scripts/webui_playground.py
  - source: relauncher.py
    dest: scripts/relauncher.py
  - source: txt2img.yaml
    dest: txt2img.yaml
  - source: webui.yaml
    dest: configs/webui/webui.yaml
  - source: scripts/frontend/__init__.py
    dest: scripts/frontend/__init__.py
  - source: scripts/frontend/css_and_js.py
    dest: scripts/frontend/css_and_js.py
  - source: scripts/frontend/frontend.py
    dest: scripts/frontend/frontend.py
  - source: scripts/frontend/ui_functions.py
    dest: scripts/frontend/ui_functions.py


