ARG PYTORCH_IMAGE=hlky/pytorch:1.12.1-runtime

FROM ${PYTORCH_IMAGE}
SHELL ["/bin/bash", "-c"]

WORKDIR /install

RUN apt-get update && \
    apt-get install -y wget curl git build-essential zip unzip nano openssh-server libgl1 cargo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#ubuntu 22.04 starts carrying b3sum upstream. pytorch is still on 18.04
RUN cargo install b3sum && cp /root/.cargo/bin/b3sum /usr/bin

COPY ./requirements.txt /install/

RUN /opt/conda/bin/python -m pip install -r /install/requirements.txt

RUN /opt/conda/bin/conda clean -ya
