# This file is part of stable-diffusion-webui (https://github.com/sd-webui/stable-diffusion-webui/).

# Copyright 2022 sd-webui team.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>. 

version: '3.3'

services:
  stable-diffusion:
    container_name: sd-webui
    image:  stable-diffusion-webui:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    volumes:
      - .:/sd
      - ./outputs:/sd/outputs
      - ./model_cache:/sd/model_cache
      - ~/.huggingface/token:/root/.huggingface/token
      - root_profile:/root
    ports:
      - '7860:7860'
      - '8501:8501'
    healthcheck:
      test: curl --fail http://localhost:8501 --head || curl --fail http://localhost:7860 --head || echo 1
      interval: 30s
      timeout: 1s
      retries: 10

volumes:
  root_profile:
