---
name: "tagged-release"

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}
