---
name: "tests"

on:
  push:
  pull_request:
    types:
      - "opened"
      - "closed"
      - "reopened"
      - "synchronize"

jobs:
  gh_tests:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0

      - id: "yarn-cache"
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: "actions/cache@v2.1.6"
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: "yarn install --frozen-lockfile"
      - run: "yarn lint"
      - run: "yarn build"
      - run: "yarn jest --env=node --colors --forceExit"

      - uses: "./packages/keybase-notifications"
        if: always()
        with:
          job_status: ${{ job.status }}
          opensentinel_token: ${{ secrets.OSL_TOKEN }}
